import type { Metadata } from "next";
import { Providers } from "./providers";
import { Helmet } from "react-helmet";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

// Structure Page For SEO Optimazed
const structData = {
    "@context": "https://schema.org",
    "@type": "BlogPosting",
    author: [
        {
            "@type": "Person",
            name: "Jane Doe",
        },
    ],
    datePublished: "2023-02-16T09:00:00.000Z",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <script key="structured-1" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structData) }} />
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
